name: ros

on:
  push:
    branches: [ ros2_foxy ]
  pull_request:
    branches: [ ros2_foxy ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: testing}
          - {ROS_DISTRO: foxy, ROS_REPO: main}

    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

